const puzzleNames = [
	['paintbynumbers_blackorwhite', ['paint by numbers (black or white)']],
	['hitori_diagonal', ['hitori (diagonal)']],
	['snakes', ['snakes', 'paths: snakes']],
	['japanese_columndance', ['japanese column dance']],
	['fillomino_futoshiki', ['fillomino (futoshiki)']],
	['find5pairs', ['find 5 pairs']],
	['inversetetorominodivision', ['逆ヒントテトロミノ分割']],
	['findthematchingsets', ['find the matching sets']],
	['crisscross_double', ['double criss-cross']],
	['allorone', ['all or one']],
	['japanese_railway', ['japanese railway']],
	['fillomino_distinctshapes', ['fillomino (distinct shapes)']],
	['whiteblacktetromino', ['白テトロミノ→黒テトロミノ']],
	['battleships_hex', ['battleships (hex)']],
	['sunglasses', ['サングラス', 'sunglasses']],
	['magicsnail', ['magic snail']],
	['boxof2or3', ['box of 2 or 3']],
	['spolicy', ['spolicy']],
	['crackiton', ['crack it on']],
	['skyscrapers_irregular', ['幾何学ビルディング']],
	['easyas_lits', ['easy as lits']],
	['skyscrapers_fullevens', ['skyscrapers (full evens)']],
	['hexa7', ['hexa 7']],
	['paintbynumbers_some', ['paint by some numbers']],
	['pentominorelations', ['pentomino relations']],
	['battleships_differentfleet', ['battleships (different fleet)', 'irregular battleships']],
	['buttons', ['buttons']],
	['kakuro_fillin', ['フィルインサムクロス']],
	['yajilin_regions', ['ヘヤジリン', 'yajilin (regions)']],
	['tetorominodivision', ['テトロミノ分割']],
	['coins', ['coins']],
	['compass', ['compass']],
	['tangledwords1', ['アロージグザグクロス']],
	['yajilin_rows', ['rows yajilin', 'loop: rows yajilin']],
	['starbattle', ['スターバトル', 'star battle', 'objects: star battle']],
	['inaiinaiba', ['いないいないバー']],
	['masyu_blackened_alternating', ['masyu (blackened, alternating)']],
	['tasquare', ['たすくえあ', 'tasquare']],
	['japanesesums', ['japanese sums']],
	['coral_encoded', ['coded coral']],
	['paradesums', ['parade sums']],
	['skyscrapers_thermo', ['thermo-skyscrapers']],
	['aidabeya', ['相ダ部屋']],
	['products_antiknight', ['products (antiknight)']],
	['darts', ['darts']],
	['gaps_notouch', ['gaps (no touch)', 'gaps', 'star gaps']],
	['coins_diagonal', ['coins (diagonal)']],
	['easyas_iso', ['easy as (iso)', 'easy as... (iso)']],
	['japanese_honeyislands', ['ハニーアイランド', 'japanese honey islands']],
	['minesweeper_pills', ['ダイナマイトパズル', 'minesweeper (pills)']],
	['findthetriplets', ['find the triplets']],
	['skyscrapers_diagonal', ['skyscrapers (diagonal)', 'skyscrapers with diagonals']],
	['vama', ['vama']],
	['cave', ['バッグ', 'cave', '洞--hora']],
	['twopa', ['twopa']],
	['codeddivision', ['ノータッチ覆面分割']],
	['wordsearch_bent', ['bent word search']],
	['kuromasu_product', ['kuromasu (product)']],
	['wolvesandsheep', ['ヤギとオオカミ', 'goats and wolves']],
	['snake_length', ['snake (length, ends)', 'snake', 'snake with length']],
	['starwars', ['star wars']],
	['pentomino_battleships', ['ペントミノバトルシップ']],
	['pentominous_borders', ['pentominous (borders)', 'pentominous borders']],
	['pentoblokus', ['pento-blokus']],
	['primepath', ['prime path']],
	['skyscraper_nurikabe', ['skyscraper nurikabe', 'shading: skyscraper nurikabe']],
	['slitherlink_outliars', ['slitherlink (out-liars)', 'slitherlink out-liars']],
	['anglers', ['anglers', 'フィッシング']],
	['slitherlink_liars', ['ウソつきループメーカー']],
	['arukone_cross', ['arukone with crossings']],
	['columndance', ['column dance']],
	['futoshiki_nonconsecutive', ['futoshiki (nonconsecutive)']],
	['curvedata', ['カーブデータ']],
	['kakuro_nonconsective', ['不連続サムクロス']],
	['endpoints_hex', ['endpoints (hex)']],
	['yinyang', ['しろまるくろまる', 'yin-yang']],
	['doppelblock_set_diagonals', ['doppelblock (set, diagonals)']],
	['maze', ['maze', 'labyrinth']],
	['pillboxes', ['pillboxes']],
	['loop_tapa', ['loop (tapa)']],
	['blokus', ['blokus', 'blokus (tetriminoes)', 'blokus (pentominoes)']],
	['fillintheblanks', ['what\'s next?', 'fill in the blanks']],
	['nurikabe_pairsums', ['nurikabe (pair sums)']],
	['sums', ['sums']],
	['easyas', ['abcプレース', 'easy as abc', 'easy as...', 'easy as', 'easy as abcd']],
	['fillomino_offbyone', ['fillomino (off-by-one)']],
	['slidingblocks', ['sliding blocks']],
	['numberparades', ['number parades']],
	['suguru', ['suguru']],
	['fourwinds_encoded', ['覆面ウォールロジック']],
	['paintbythree', ['paint by three', 'paint by threes']],
	['nurikabe_norect', ['四角禁止の間■仕■切■り']],
	['spiralgalaxies_battleships', ['spiral galaxies + battleships']],
	['swisscrosses2color', ['swiss crosses (2-color)']],
	['indexsums', ['index sums']],
	['shapesweeper', ['shapesweeper', 'shape minesweeper']],
	['snake_stripedlengthends', ['snake (striped, length, ends)']],
	['hitori_letter', ['letter hitori']],
	['snake_striped', ['snake (ends,striped)']],
	['battleships', ['バトルシップ', 'battleships']],
	['japanesesums_withzero', ['japanese sums with zeroes']],
	['chessattacks', ['chess attacks']],
	['minesweeper', ['ボンバーパズル', 'minesweeper']],
	['skyscrapers', ['ビルディング', 'skyscrapers', 'ビルディングパズル']],
	['sixwinds', ['six winds']],
	['ayda', ['ayda']],
	['statuepark_noreflection', ['statue park (no reflection)']],
	['shikaku', ['四角に切れ', 'regions: shikaku', 'shikaku']],
	['elasticwords', ['elastic words', 'word cobweb']],
	['footballpass', ['football pass']],
	['pills', ['pills']],
	['tents_diagonaltwos', ['tents (diagonal, twos)']],
	['magnets_diagonal', ['magnets (diagonal)']],
	['slant', ['ごきげんななめ', 'ループはいやよ', 'slalom']],
	['skyscrapers_hex', ['skyscrapers (hex)', 'skyscrapers']],
	['hashiwokakero_encoded', ['hashiwokakero (encoded)', 'encrypted hashiwokakero']],
	['star_battleships', ['star battleships']],
	['shortestdistances', ['shortest distances']],
	['walls', ['walls']],
	['lakes', ['lakes', 'shading: lakes']],
	['illumination', ['イルミネーション']],
	['arithmeticsquare_encoded', ['arithmetic square (encoded)', 'arithmetic square (encrypted)']],
	['latinsquare', ['ラテンスクエア']],
	['adjacencysums', ['adjacency sums']],
	['barplace', ['バールプレース']],
	['yajilin_minesweeper', ['yajilin (minesweeper)']],
	['palindromesornot', ['palindromes or not']],
	['balance', ['balance']],
	['shakashaka', ['シャカシャカ', 'shakashaka']],
	['yajilin_battleships', ['yajilin (battleship)', 'yajilin (battleships)']],
	['easyas_loop', ['easy as (loop)']],
	['dosokuloop', ['同側ループ']],
	['doppelblock_skyscrapers', ['doppelblock skyscrapers']],
	['lightandshadow', ['light and shadow']],
	['endpoints', ['endpoints']],
	['doppelblock_set', ['doppelblock (set)', 'doppelblock (variable)']],
	['skyscrapers_x', ['中庭ビルディング']],
	['yajilin', ['ヤジリン', 'yajilin', 'ループであろー']],
	['hiroimono', ['碁石拾い', 'hiroimono']],
	['masyu_singleliar', ['masyu (single liar)']],
	['l', ['える']],
	['nuraf', ['nuraf']],
	['magicsummer', ['magic summer']],
	['doppelblock_unknownset', ['doppelblock (unknown set)']],
	['anglers_cave', ['anglers’ cave']],
	['letterbags', ['letter bags']],
	['fillomino_checkerboard', ['fillomino checkerboard']],
	['clouds', ['clouds', 'rain clouds (radar)', 'rain clouds']],
	['kakuro_consecutive', ['consecutive kakuro']],
	['placebyproduct', ['place by product']],
	['arithmeticsquare_withzero', ['arithmetic square with zero']],
	['slitherlink_dual', ['似て非なるループメーカー']],
	['parkinglot', ['パーキング', 'parking lot']],
	['foursnails', ['four snails']],
	['jigsawpuzzle', ['ジグソーパズル', 'jigsaw puzzle']],
	['foldin_crisscross', ['fold-in criss-cross']],
	['cave_inorout', ['内外不明のcave']],
	['slitherlink', ['スリザーリンク', 'slitherlink', 'fences (slitherlink)', 'ループメーカー']],
	['scrabble_2crossings', ['scrabble (2+ crossings)']],
	['arithmeticsquare_unassigned', ['arithmetic square (unassigned)']],
	['minsweeper', ['minsweeper']],
	['skyscrapers_dominos', ['ドミノビルディングパズル']],
	['myopia', ['myopia']],
	['crossdivision', ['クロス分割']],
	['skyscrapers_uncounted', ['ガラスの街のビルディング', 'uncounted skyscrapers']],
	['wordsearch', ['シークワーズ', 'word search', 'wordsearch']],
	['tripletsums', ['triplet sums']],
	['battleships_iso', ['battleships (iso)']],
	['fourwinds', ['ウォールロジック', 'four winds']],
	['maxloop', ['最大値ループ']],
	['kakuro_parity', ['偶か奇かサムクロス']],
	['inverselitso', ['inverse litso']],
	['hidato', ['hidato']],
	['dominoconstruction', ['domino construction']],
	['yajilin_castlewall', ['yajilin (castle wall)']],
	['lits', ['lits', 'テトロミノリンク']],
	['scrabble', ['セルフスケルトン', 'scrabble', 'scrabble (multiple letters)', '親切なセルフスケルトン', 'scrabble (unused word)', 'scrabble (letters)']],
	['coral_overlapping', ['coral (overlapping)']],
	['masyu_notouch', ['no-touch masyu', 'loop: no-touch masyu']],
	['slashpack', ['slash pack']],
	['shimatotetrominos', ['島とテトロミノ']],
	['inequalities', ['inequalities']],
	['alphametics', ['覆面算', 'alphametics']],
	['dominion', ['dominion']],
	['kakuro_parity3renzokukinshi', ['奇数偶数3連続禁止のサムクロス']],
	['pentominous_spiralgalaxies', ['pentominous (spiral galaxies)']],
	['sky_tomtom', ['skytomtom']],
	['shapesweeper_skyscrapers_connected', ['connected-shapesweeper-skyscrapers']],
	['gaps', ['gaps', 'objects: gaps']],
	['builda_crisscross', ['build a criss-cross']],
	['fillomino_123', ['fillomino (123)']],
	['balancescales', ['balance scales']],
	['loop_dutch', ['loop (dutch)']],
	['gaps_notouch_offbyone', ['gaps (no touch, off by one)']],
	['equations', ['equations']],
	['tomtom_operations', ['tomtom (operations)', 'numbers: tomtom operations', 'tom tom (operations)']],
	['magnets_toroidal', ['magnets (toroidal)']],
	['full_tapa', ['full tapa']],
	['makeamaze', ['make a maze']],
	['endpoints_iso', ['endpoints (iso)']],
	['pentominoareas', ['ペントミノエリア', 'pentomino areas']],
	['counttheshapes', ['count the shapes', 'count shapes']],
	['skyscrapers_park', ['skyscrapers (park)']],
	['oldmaid', ['old maid']],
	['escapethegrandprix_mastermind', ['escape the grand prix: mastermind']],
	['alphabetblocks', ['alphabet blocks']],
	['simpleloop_shaded', ['loop (shaded)']],
	['shikaku_encoded', ['覆面ナンバーエリア']],
	['crisscross_crowded', ['criss-cross (crowded)']],
	['escapethegrandprix', ['escape the grand prix']],
	['sum_battleships', ['sum battleships']],
	['productlines', ['product lines']],
	['fillomino_nonconsective', ['不連続な隣人']],
	['japanesesums_loop', ['japanese sums and loop']],
	['tictaclogic', ['tic-tac-logic']],
	['baca', ['baca']],
	['skyscraper_blocks', ['skyscraper blocks']],
	['teraxx', ['tera xx']],
	['cryptarithm', ['虫食い算', 'arithmetic separation']],
	['easyas_hex', ['easy as (hex)', 'easy as... (hex)']],
	['easyas_no2x2', ['easy as (no 2×2)']],
	['sudoku', ['数独', 'ナンプレ', 'sudoku']],
	['ripplearrows', ['ripple arrows']],
	['tapa_lits', ['tapa (lits)', 'tapa (lits rules)']],
	['trid', ['trid']],
	['kuromasu_starbattle', ['kuromasu (star battle)']],
	['tapa_unknownscoupled', ['tapa (unknowns, coupled)']],
	['pentominoes', ['ペントミノプレース', 'tetromino search', 'pentominoes']],
	['binary_parquet', ['binary parquet']],
	['shikaku_spiralgalaxies', ['四角か対称か']],
	['araf', ['araf']],
	['skyscrapers_encoded', ['覆面ビルディングパズル', 'skyscrapers (encoded)']],
	['futoshiki', ['futoshiki']],
	['nofourinarow', ['no four in a row']],
	['stacked', ['stacked']],
	['yinyang_equalregions', ['yin-yang (equal regions)']],
	['nurikabe_battleships', ['nurikabe battleships']],
	['castlewall', ['castle wall']],
	['crossranges', ['crossranges']],
	['mastermind', ['マスターマインド', 'mastermind']],
	['doublechoco', ['ダブルチョコ', 'double choco']],
	['letterweights', ['覆面サム', 'letter weights']],
	['snake_pit', ['snake pit']],
	['loopportals', ['loop (portals)']],
	['hexiom', ['hexiom']],
	['pills_hex', ['pills (hex)', 'pills']],
	['associationfootball', ['association football']],
	['findthedifferences', ['間違い探し', 'find the differences']],
	['simultaneous_equations', ['小町算', 'simultaneous equations']],
	['shakashaka_encoded', ['覆面シャカシャカ', 'shakashaka (encoded)']],
	['futoshiki_hex', ['futoshiki (hex)']],
	['baca_givenset', ['baca (given set)']],
	['japanese_parkinglot', ['japanese parking lot']],
	['easyas_second', ['easy as (second)']],
	['findthepair', ['find the pair']],
	['capsules', ['capsules']],
	['japanesesums_unknowns', ['unknown japanese sums']],
	['fillomino_bigcells', ['fillomino (big cells)']],
	['sanrenzokukinshinooxplace', ['三連続禁止の○×プレース']],
	['wordsearch_count', ['word search (count)']],
	['arrows', ['arrows']],
	['skyscrapers_afternoon', ['afternoon skyscrapers']],
	['maxiloop', ['maxi loop']],
	['postits', ['post-its']],
	['minesweeper_encoded', ['覆面ボンバーパズル']],
	['akari', ['美術館', 'akari', 'bulbs (akari)']],
	['abcbox', ['abc-box']],
	['recto', ['recto']],
	['futoshiki_iso_sudoku', ['futoshiki (iso, sudoku)']],
	['shapedivision', ['shape division']],
	['commonletters', ['common letters']],
	['shiteihoukouigaishinkoukinshimaze', ['指定方向以外進行禁止メイズ']],
	['fourwinds_withparks', ['four winds with parks']],
	['trianglewordsearch', ['triangle word search']],
	['increasingdistances', ['increasing distances']],
	['slitherlink_fullevens', ['slitherlink (full evens)']],
	['nurikabe_symmetric_encoded', ['symmetric encrypted nurikabe']],
	['arithmeticsquare', ['クロスマッス', 'arithmetic square', 'cross math', 'numbers: arithmetic square', '吉例クロスマッス']],
	['hundred', ['hundred']],
	['fourwinds_toroidal', ['シームレスウォールロジック']],
	['blackoutmath', ['blackout math']],
	['nanro_signpost', ['nanro signpost', 'nanro (signpost)']],
	['fillintheblank', ['fill in the blank']],
	['snake_myopia', ['snake (myopia)']],
	['swisscrossessum', ['swiss crosses (sum)']],
	['pentopia', ['pentopia', 'pentominoes (myopia)']],
	['magnets_horseshoes', ['magnets (horseshoes)']],
	['pyramid', ['ピラミッド', 'pyramid']],
	['masyu_colorblind_yajilin', ['masyu (colorblind) + yajilin']],
	['ilus', ['ilus']],
	['skyscrapers_dominoconstruction', ['skyscrapers domino construction']],
	['battleships_indexsums', ['battleships (index sums)']],
	['numbersnake_orthogonal', ['number snake (orthogonal)']],
	['lightsandswitches', ['lights and switches']],
	['numberconnection', ['数字つなぎ', 'number connection']],
	['arithmetic', ['arithmetic']],
	['chess', ['chess']],
	['lits_tapa', ['lits (tapa)']],
	['skyscrapers_shapes', ['shapeskyscrapers']],
	['japanesesums_hex', ['japanese sums (hex)', 'japanese sums']],
	['graffiti', ['graffiti']],
	['brokencalculator', ['broken calculator']],
	['heyawake', ['へやわけ', 'heyawake']],
	['slitherlink_bigcells', ['slitherlink (big cells)']],
	['wordtsunagi', ['ワードつなぎ']],
	['hashiwokakero', ['橋をかけろ', '島めぐり']],
	['division', ['ブロック分割', 'pentomino division']],
	['doppelblock_parquetliar', ['doppelblock (parquet, liar)']],
	['hungarian_numberlink', ['hungarian numberlink']],
	['squaredivision', ['square division']],
	['characterbattle', ['character battle']],
	['rippleeffect', ['波及効果', 'ripple effect', 'なわばりプレース']],
	['tomtom', ['tomtom', 'numbers: tomtom', 'tom tom']],
	['rook_hidato', ['rook hidato']],
	['yajirushitenbin', ['やじるしてんびん']],
	['darkknightlines', ['dark knightlines']],
	['yajilin_shapes', ['yajilin-shapes']],
	['easyas_whatnumber', ['easyas-whatnumber']],
	['loop_pentominowalls_maxlengths', ['loop (pentomino walls, max lengths)']],
	['easyas_japanese_railways', ['easy as japanese railways']],
	['pointingatthecrowd', ['pointing at the crowd']],
	['pentominous', ['ノータッチ・ペントミノ分割', 'pentominous']],
	['slitherlink_noswiss', ['slitherlink (no swiss)']],
	['whatsnext', ['what’s next?']],
	['yajinurikabelin', ['yajinurikabelin']],
	['yajilin_hex', ['六角ループであろー', 'yajilin (hex)']],
	['topheavy', ['頭でっかちナンプレ', 'top heavy']],
	['slitherlink_unequallengths', ['slitherlink (unequal lengths)']],
	['quiz', ['クイズ', 'mini quiz']],
	['easyas_fuzuli', ['easy as (fuzuli)', 'easy as... (fuzuli)']],
	['fillomino_hex', ['fillomino (hex)']],
	['matches', ['matches']],
	['battleships_phrase', ['battleships (phrase)']],
	['chains', ['chains']],
	['yinyang_noswiss', ['yin-yang (no swiss)']],
	['lighthouses', ['lighthouses']],
	['countries', ['countries']],
	['slitherlink_wolvesandsheep', ['slitherlink (wolves and sheep)', 'wolves and sheep fences']],
	['kakuro_grouping', ['大中小サムクロス']],
	['nurikabe_symmetry', ['nurikabe (symmetry)']],
	['primeplace', ['prime place']],
	['arithmeticsquare_unknownresults', ['arithmetic square (unknown results)']],
	['thermometers_iso', ['thermometers (iso)']],
	['kropki', ['kropki']],
	['counttheknightpaths', ['count the knight paths']],
	['easyas_firstorsecond', ['easy as first or second abcd']],
	['skyscrapers_connected', ['ビルディングの輪']],
	['hexislands', ['hex islands']],
	['fillomino_snake_encoded', ['cipher-fillomino-snake']],
	['snakystationloop', ['snaky station loop']],
	['maximallengths', ['maximal lengths']],
	['arithmeticsquare_operations', ['arithmetic square operations']],
	['snake_three', ['3匹のスネーク']],
	['nanro', ['ナンロー', 'nanro']],
	['paintbynumbers', ['お絵かきロジック', 'paint by numbers']],
	['products', ['products']],
	['yinyang_slitherlink', ['yin-yang slitherlink']],
	['skyscrapers_multiview', ['multiview skyscrapers']],
	['tetroscope', ['tetroscope']],
	['snake_offbyone', ['嘘つきスネーク']],
	['nurikabe_snake', ['nurikabe (snake)']],
	['products_offbyone', ['products (off-by-one)']],
	['spans', ['spans']],
	['kurotto', ['クロット', 'kurotto']],
	['snakyloop_regions', ['snaky loop (regions)']],
	['heyawake_irregular', ['heyawake (irregular)']],
	['passwordpath', ['password path']],
	['hydra', ['hydra']],
	['arrow_latinsquare', ['arrow latin square']],
	['hideout_fences', ['hideout fences']],
	['kakuro', ['カックロ', 'cross sums (kakuro)', 'kakuro', 'サムクロス']],
	['esayas_second', ['esayas-second']],
	['doppelblock_bigcells', ['irregular doppelblock']],
	['oases', ['oases']],
	['snake', ['スネーク', 'snake (ends)', 'snake', 'paths: snake', 'snake (with ends)']],
	['differentneighbors', ['different neighbors']],
	['simpleloop', ['シンプルループ', 'loop: simple loop', 'simple loop', 'loop']],
	['myopia_battleships', ['myopia バトルシップ']],
	['crisscross_tomtom', ['criss-cross (tomtom)']],
	['doppelblock_variable', ['doppelblock (variable)']],
	['mastermind_nurikabe_yajilin', ['mastermind-nurikabe-yajilin']],
	['kakuro_order', ['お行儀のよいサムクロス']],
	['slitherlink_liardiagonal', ['liar diagonal slitherlink']],
	['fuzuli', ['fuzuli']],
	['abba', ['abba']],
	['shikaku_offbyone', ['嘘つきナンバーエリア', 'shikaku liars', 'shikaku (off-by-one)']],
	['fillomino', ['フィルオミノ', 'fillomino', 'regions: fillomino', '見知らぬ隣人']],
	['minesweeper_double', ['ダブル・ボンバーパズル', 'double minesweeper', 'minesweeper (double)']],
	['builda_wordsearch', ['build a word search']],
	['slitherlink_hex', ['六角ループメーカー', 'slitherlink', 'slitherlink (hexagonal)']],
	['police', ['police']],
	['japanesearrows', ['何種類?', 'japanese arrows']],
	['cave_bigcells', ['cave (big cells)']],
	['kansetsuarrowplace', ['間接アロープレース']],
	['snake_cities', ['snake cities']],
	['crisscross_unknowns', ['虫食いスケルトン']],
	['litso', ['litso']],
	['modes', ['modes']],
	['doppelblock', ['ビトィーンサム', 'doppelblock']],
	['tetrominous', ['tetrominous']],
	['honeyislands', ['ハニーアイランド', 'honey islands']],
	['tapa_encoded', ['tapa logic']],
	['nurikabe', ['ぬりかべ', 'nurikabe', 'islands (nurikabe)', 'shading: nurikabe', '間■仕■切■り']],
	['battlestars', ['battle stars']],
	['tetrominous_secondseen', ['tetrominous (second seen)']],
	['peggedtetrominoes', ['ペグオミノ']],
	['statuepark', ['statue park', 'ペントミノプレース']],
	['infection', ['数コロ', 'infection']],
	['arukone', ['アルコネ', 'arukone', 'arukone (numberlink)', 'paths: arukone', 'アルファベットコネクション', 'numberlink']],
	['crackthecode', ['crack the code']],
	['tetromino_division', ['tetromino division']],
	['dominosearch', ['ドミノ分割', 'domino search', 'domino division']],
	['magnets', ['マグネット', 'magnets']],
	['starryroad', ['starry road']],
	['skyscrapers_relations', ['skyscrapers (relations)']],
	['arrowmaze', ['arrow maze', 'アローメイズ']],
	['meandering_wordsearch', ['meandering wordsearch']],
	['findthematch', ['find the match']],
	['slovaksums', ['slovak sums']],
	['doppelblock_diagonals', ['doppelblock (diagonals)']],
	['dominocastle', ['ドミノキャッスル']],
	['skyscrapers_bigcells', ['skyscrapers (big cells)']],
	['nofourinarow_overlapping', ['no four in a row (overlapping)']],
	['coral', ['コーラル', 'coral']],
	['twinsweepers', ['ツインスイーパー']],
	['spiralgalaxies', ['天体ショー', 'spiral galaxies', '点対称分割']],
	['thermometers', ['thermometers']],
	['thermometers_hex', ['thermometers (hex)']],
	['sky_neighbors', ['sky-neighbors']],
	['arithmeticalcity', ['arithmetical city']],
	['skyscraper_sums', ['skyscraper sums']],
	['meanderingnumbers', ['にょろにょろナンバー', 'count number', 'meandering numbers', 'worm farm (count number)']],
	['fillomino_rectangles', ['fillomino rectangles', 'regions: fillomino rectangles']],
	['meanderingwords', ['にょろにょろワード', 'meandering words']],
	['kazoeteumete', ['数えて埋めて']],
	['towerdefense', ['tower defense']],
	['tapa_transparent', ['tapa (transparent)']],
	['esayas_whatnumber', ['注文の多いabcプレース']],
	['japanesesums_hitori', ['japanese sums (hitori)']],
	['kropki_hex', ['kropki (hex)', 'kropki']],
	['easyas_notouch', ['ななめにくっつかないabcプレース', 'easy as... no touching', 'easy as... (no touch)']],
	['letterpairs', ['letter pairs']],
	['easyas_kunekune', ['くねくねabcプレース', 'くねくねabcdプレース']],
	['nuribou', ['ぬりぼう', 'nuribou']],
	['equalloop', ['イコールループ']],
	['tigerinthewoods', ['tiger in the woods']],
	['sname', ['sname']],
	['numbersnake_diagonal', ['number snake (diagonal)']],
	['fillomino_iso', ['fillomino (iso)']],
	['slitherlink_pentominoes', ['slitherlink (pentominoes)', 'pento-slitherlink']],
	['yajilin_iso', ['yajilin (iso)']],
	['wasyas_hex', ['easy as (hex)', 'easy as...']],
	['masyu', ['ましゅ', 'masyu', 'パールネックレス']],
	['tapa', ['tapa']],
	['crystalmine', ['crystal mine']],
	['slitherlink_encoded', ['覆面スリザーリンク', 'slitherlink (encoded)']],
	['japanese_snake', ['japanese snake (ends)']],
	['tapa_wall', ['tapa (wall)']],
	['hitori', ['ひとりにしてくれ', 'hitori']],
	['shikaku_unknowns', ['?入りナンバーエリア']],
	['nanro_signpost_yinyang', ['nanro signpost (yin-yang)']],
	['summon', ['summon']],
	['crisscross', ['スケルトン', 'crisscross', 'criss-cross']],
	['railway', ['railway']],
	['connections', ['connections']],
	['everysecondturn', ['every second turn']],
	['instructionlessmachine', ['instructionless machine']],
	['elasticbands', ['elastic bands']],
	['fillomino_encoded', ['fillomino (encoded)', 'fillomino (cipher)']],
	['spiralgalaxies_tetrominoes', ['spiral galaxies + tetrominoes', 'spiral galaxies (tetrominoes)']],
	['wordsearch_liar', ['嘘つきシークワーズ']],
	['photostream', ['photo stream']],
	['antidominosnakyloop', ['antidomino snaky loop']],
	['chouhoukeidivision', ['長方形分割']],
	['tetrominoes', ['テトロミノプレース']],
	['doppelblock_2', ['ビトィーン2サム']],
	['kuromasu', ['黒どこ', 'kuromasu', 'トラップサーチ']],
	['starbattle_halfregion', ['half-region star battle', 'objects: half-region star battle']],
	['pyramidclimbers', ['pyramid climbers']],
	['masyu_colorblind', ['masyu (colorblind)']],
	['shapeplacement', ['shape placement', 'テルミーラブ']],
	['snake_dotted', ['dotted snake']],
	['greaterwall', ['greater wall']],
	['neighbors', ['neighbors']],
	['boomerangs', ['boomerangs']],
	['tents', ['ベストテントサイト', 'tents', 'tents and trees']],
	['notliketheothers', ['not like the others']],
	['endsum', ['エンドサム']]
]
